### ISSUE TITLE
Research: Encryption Options

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#1]
Need to look into what options are available for encryption. The pros and cons of each option. We would want to get options for two:

- [ ] Lighter encryption. Doesn't use much processing power and it quick. Only needs to be decently secure. 
- [ ] Strong encryption. Can use a higher amount of processing power and takes longer. Needs to be very secure. 

If there is a encryption algorithm that is the best of these two, that could be used instead. Keep in mind this is for over the network. So, it needs to be able to establish a handshake before to decide between the hosts what is used for encryption. Can't be static. 

This is for encrypting the payload only, not the handshake. We should have a algorithm decided but we also want another option depending how heavy or light that one is.

**Comment by tuckplace** [comment]
Need a encryption that carries out a handshake and encrypts the payload.

**Comment by tuckplace** [comment]
Needs to be able to run on a low power system and be very secure. If not possible, could have two options

**Comment by doberzan** [comment]
# Asymmetric Key Exchange
- ED25519: Elliptic-curve Digital Signature Algorithm
- Python module: `ed25519` https://pypi.org/project/ed25519/

# Symmetric Data Encryption
- Python module: `PyCrypto` https://pypi.org/project/pycrypto/
- AES-CBC-256 "Cipher block chaining" for data/payload encryption

# Recommendation/Implementation **ASK WEI PING KATE**
- My recommendation is implementing an asymmetric handshake/key exchange with the public key algorithm ED25519 `Elliptic-curve Digital Signature Algorithm`. Then using symmetric data encryption with `AES-CBC` for the message payload with HMAC-SHA256 as the message integrity verification.

**Comment by mypleasure370** [comment]
Weiping said she thought declans plan was a good one. She didnt have any immediate recommendations but she would let me know if she discovered anything that might help us further

**Comment by tuckplace** [comment]
Spoke with Dr. Papa, he recommended SSL for quick and dirty.

**Comment by tuckplace** [comment]
Going with Elliptic Curve.  This is because it is very secure and has a small key size for easy processing.
