### ISSUE TITLE
Testing: Client Class Functionality

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#10]
Please see [this ticket](https://github.com/cs-utulsa/Encrypted-Chat-Service/issues/7) before starting this one.  
  
Purpose of this ticket is to test the client class. Need to verify it is fully working. Testing should be done in the QA branch along with any changes needed to the code. Once it has been fully tested, it can be pushed to production.   
  
Need to push this class to it's limits. Make sure it fully works. If anything is not working, please work with the original author to fix it.  This class must contain error checking, and detailed comments in the code.

- [x] Includes a constructor that takes in a value for the port number and IP addresses
- [x] Only tries a connection when the connect method is called
- [x] Class is able to create a connection
- [x] Connect method returns connected socket when a connection is properly made
- [x] When a connection is not made, returns null for the socket value
- [x] Fully commented.
- [x] Error handling for invalid inputs.

**Comment by JR1178** [comment]
Fully commented, added a few try/except blocks, and tested to ensure everything still works.
