### ISSUE TITLE
Testing: Chat Class Functionality

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#11]
Please see [this ticket](https://github.com/cs-utulsa/Encrypted-Chat-Service/issues/8) before starting this one.  
  
Purpose of this ticket is to test the chat class. Need to verify it is fully working. Testing should be done in the QA branch along with any changes needed to the code. Once it has been fully tested, it can be pushed to production.   
  
Need to push this class to it's limits. Make sure it fully works. If anything is not working, please work with the original author to fix it. This class must contain error checking, multiple messages able to be sent without a response, and detail comments in the code.

- [x] Main method runs and prompts user for port and IP address
- [x] Properly intakes port and IP address
- [x] Calls the client class first to attempt a connection
- [x] If the client class returns null, switches to server class
- [x] Class server class to listen for a connection
- [x] If a connection can not be made and the sever class returns null, must prompt the user. Choices are to restart the program or exit.
- [x] When a connection is made, chat class is able to handle communication back and fourth. 
- [x] Chat messages are printed on both sides with the proper remote or local tag in front. 
- [x] EXIT command properly exits.
- [x] When invalid data is input for the IP address or port, error is handled and user is prompted again. 
- [x] Is fully commented.
- [x] Multiple messages can be sent without a response.

**Comment by piangno** [comment]
Only the client can exit it
