### ISSUE TITLE
Research: File Transfer Options 

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#22]
Purpose of this story is to look into options for file transfer. Need a method that can also be encrypted and decrypted. 

- [x] Method for reading file in.
- [x] Method for re-creating file on other side.
- [x] File can be encrypted before being sent and decrypted when it arrives in the same way chats are.
- [x] Needs to be as simple as possible.

**Comment by EWFranks** [comment]
FTPS vs SFTP

**Comment by EWFranks** [comment]
**Method for reading file in**

- Using a FileInput node that reads in a file directory on an FTP server. This will allow the translation of messages from the contents of those files.

**Method for re-creating file on other side**

- Using our custom SSL method the file will be be encrypted and then duplicated on the server and decrypted when a verified user downloads or views the file. 
This is done with a FileOutput node that is generated from a single message that is received, which writes to an empty file until the full message is finished.
