### ISSUE TITLE
Coding: Write Encrypt Class

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#25]
Please read feature release 1 architecture before starting this story.

This class should be called by chat to encrypt a payload before sending it or decrypt upon receiving it. The constructor should take the ECC key as an argument. It should have a method that takes in the message payload and returns it encrypted. The other method should take a encrypted payload and return it decrypted. These are called by the chat class when sending or receiving messages.

Please also see this [link](https://pycryptodome.readthedocs.io/en/latest/src/cipher/cipher.html)

**Comment by dawsonjones2020** [comment]
Can easily use the Fernet class in place of this. No need to code our own class.

[Usage](https://cryptography.io/en/latest/fernet/)

Requires pip install cryptography and fernet. Can create an object with `Fernet(key)` and can encrypt or decrypt using `.encrypt(bytes)` and `.decrypt(bytes)`
