### ISSUE TITLE
Research: Encryption for File Transfer

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#38]
This issue can only be done once a file transfer option has been researched and decided on. Need to investigate a way to encrypt the files before sending and decrypt them after receiving. Needs to use ECC key and be able to be sent over a socket. 

- [x] Way to encrypt file once it has been read in
- [x] Ability to send encrypted file
- [x] Way to decrypt received file
- [x] Need outline for how this would work based on the results of the file transfer research.

**Comment by EWFranks** [comment]
FPTS is FTP using SSL 
-(Encryption) Using SSL, a secure socket layer is a security protocol that creates a encrypted link between a server and a browser on the web. This SSL methods is already established and as the message is read in the encryption class will be called to encrypt the message. The client encrypts a secret key with the server's public key, which is stores the encrypted file on the server
-(Decryption) The same process as encryption works with decrypt. But the server will decrypt the file using a different key that allows the decrypted file to be obtained by the client. Which this is already done as well.

Send Encrypted files 
-Three scenarios for transferring files will be present.
<1> Source FTPS Server to Target FTPS Server
-A middle connection that pushed files to the target FTPS and pulls files from the source server. The middle medium is by the client.
<2> Source FTPS Client to Target FTPS Client
-A middle connection is represented by the server, while the source client pushes files to the server and then the target client pulls them.
<3> Source FTPS Server to Target FTPS Client
-A middle connection is represented by a server and a client. The client pulls the file from the source server. Then the targeted client pulls files from the server.
