### ISSUE TITLE
Coding: Screens for Connection

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#41]
Please ensure you have read the [architecture](https://github.com/cs-utulsa/Encrypted-Chat-Service/wiki/Feature-Release-2:-GUI-Architecture) before starting on this story. 
  
The goal of this story is to provide screens to the user while the backend is establishing a connection. This should be a box that allows the user to see what IP and port they are trying to connect to. It should also, if possible, have a spinning wheel to show progress is still being made. 

Should an error occur during any part of the connection setup, the user should be notified the connection could not be made and given an option. Choice to exit or return to startup screen. When the connection is successful, the user is brought to the chat screen.

- [x] Appears at the proper time after a user has input the values and initiated the connection 
- [x] Can display when an error occurs
- [x] Gives user options when a error occurs. 
- [x] Should follow created mockups
- [x] Must be fully commented
- [ ] Runs in the chat class. 
- [x] Does not hinder the connection process

**Comment by tuckplace** [comment]
This issue needs to work with the current GUI setup. The areas to enter the connection information were included on the main screen. The main point here is to have a popup for connecting, with a spinning wheel. This will require a second thread.

**Comment by piangno** [comment]
About 20-30 hours (2 sprints)
