### ISSUE TITLE
Testing: Handshake Class

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#42]
Goal of this story is to ensure the handshake class is fully functional.

- [x] Handshake is properly done in a way the shared secret can not be leaked
- [x] Generates ECC key correctly on both sides
- [x] Is fully commented
- [x] Works with all existing classes
- [x] Contains any needed error handling.

**Comment by JR1178** [comment]
Completely tested and traffic is encrypted.
