### ISSUE TITLE
Pull Request: Merge Dev into QA

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#52]
**DO NOT DO THIS ISSUE UNTIL [THIS](https://github.com/cs-utulsa/Encrypted-Chat-Service/issues/51) ONE IS DONE**

Need to merge Dev into QA.

- [x] Must be done before any code in dev is modified for this sprint
- [x] Must be done before testing stories can start
- [x] Dev should remain as is after this
- [x] Do not delete any branches. 
- [x] Ensure tested code from QA is brought into dev

**Comment by dawsonjones2020** [comment]
I don't know y'all. I tried.
