### ISSUE TITLE
Coding: Write Server Class

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#6]
Before continuing, make sure you have read the [architecture.](https://github.com/cs-utulsa/Encrypted-Chat-Service/wiki/Minimum-Viable-Product-Architecture)  
  
The purpose of this ticket is to fill in the server class. For our MVP, this must be done. This class performs an active listen. It should get the port to listen on from the chat class. It listens until there is a timeout (1 minute) or a connection can be made. When a connection comes in, this class needs to complete the connection and pass it back to the chat class. This class' constructor should take the port as an int for arguments. When there is a timeout, it should pass a null socket back to the chat class.  The sockets used here must be TCP.
  
Constructor: Needs parameter for port to listen on.  
Methods:  
* public socket connect() - Returns the socket if a connection is made. Returns null if no connection is made.  
* public int getPort() - Returns port.  
* public null setPort(int port) - Sets the port value to the one in the parameter.   

[Optional] Add a main method in this class for testing. 

- [x] Create constructor
- [x] Create connect method
- [x] Create getters & setters
- [x] [Optional] Main method for testing.
- [x] Class is functional and has plenty of comments throughout.

**Comment by JR1178** [comment]
I wrote the server class for our application along with a small test script for basic server debugging. The server class, named ChatServer, listens for a connection on a given port, and establishes the connection upon attempt to connect from another host. If no connection is made in a desired timeframe, the server will time out.
