### ISSUE TITLE
Coding: Full Review and Enhancement

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#60]
This story will be a larger one. The goal is to cleanup and, where possible, enhance our existing code. A strong foundation is needed. Must be done for the following files:

chat
client
main
message
server

- [x] Where possible, code improvements made (efficiency, less lines, etc)
- [x] All code is fully commented, must include descriptions for what each block does, method descriptions and class descriptions
- [x] All code follows similar formatting

This will involve going over code you may not have written. If you have questions and don't know who wrote it, please post in the groupme.

**Comment by JR1178** [comment]
Comments were reworded and added where needed. Not many methods needed to be improved due to our output of good code.
