### ISSUE TITLE
Documentation: Update Readme

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#61]
Goal of this story is to update our readme. This readme should be the same for all branches. The readme should:

- [x] Use clear, concise formatting and language
- [x] Give instructions to use the application in both GUI and command line modes, as well as how to access each mode
- [x] Give a overview of how the application operates, the encryption implemented and what features are available.  

This story can not be done until the GUI final mockups are complete.

**Comment by EWFranks** [comment]
Done
