### ISSUE TITLE
Coding: Modification of Existing Classes to Support Sending a File

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#68]
Goal of this story is to ensure that files can be formatted (using the message class) and sent properly. The name of the file along with what format it is (.txt, .pdf. etc) need to be passed when sending a file. The receiver also must be able to receive the file and re-create the file object.

- [x] Files can be properly handled (after intake and encryption covered by other stories) and sent.
- [x] Files can be properly handled (after intake and encryption covered by other stories) and received.
- [x] Code is clean and fully functional, as well as not breaking any other functionality. 
- [x] Code is well commented

**Comment by piangno** [comment]
2 hours
