### ISSUE TITLE
Coding: Write Client Class

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#7]
Before continuing, make sure you have read the [architecture.](https://github.com/cs-utulsa/Encrypted-Chat-Service/wiki/Minimum-Viable-Product-Architecture)  
  
The purpose of this ticket is to fill in the client class. For our MVP, this must be done. This class' role is to attempt to make the connection. It's constructor should include arguments for the IP address and port it will be connecting to. When it's connect method is called, it should attempt to make the connection. It should try 5 times before giving up and passing back to the chat class. If a connection is made, this class should establish it and pass it back to the chat class. When a connection can not be made, it should pass a null socket back to the chat class.  The sockets used here must be TCP.
  
Constructor: Needs parameter for port and IP address to connect to.
Methods:
- public socket connect() - Returns the socket if a connection is made. Returns null if no connection is made.
- public int getPort() - Returns port.
- public null setPort(int port) - Sets the port value to the one in the parameter.
- public String getIP() - Returns IP address.
- public null setIP(String IP) - Sets the IP value to the one in the parameter.  

[Optional] Add a main method in this class for testing. 

- [x] Create constructor
- [x] Create connect method
- [x] Create getters & setters
- [x] [Optional] Main method for testing.
- [x] Class is functional and has plenty of comments throughout.

**Comment by piangno** [comment]
The client class is complete
