### ISSUE TITLE
Testing: Unit Testing

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#74]
Goal of this story is to complete our sprint specific assignment. Each of us need to complete 3 unit tests and 1 integration test. This is required as part of this sprint by the class.

Each unit test can be small or large. Just pick a small segment of code and ensure it works as intended for each unit test. The integration test also simply needs to ensure different parts work properly together. This could be between two methods or classes. Once you have completed your tests, add writeups of each in a comment on this issue. 

- [x] Conner - 3 unit
- [x] Kate - 3 unit
- [x] Declan - 3 unit
- [x] Eliga - 3 unit and 1 integration test. 
- [x] James - 3 unit
- [x] Joel - 3 unit
- [x] Dawson - 3 unit
- [x] Integration Test (Unassigned)
- [x] All unit tests completed and added to the sprint doc (Conner)

**Comment by EWFranks** [comment]
Unit Test the unit test is procedural, requires the block of code in addition to the next. These were ran in isolation from the chat class.
-Ran reading in the file multiple times and all successfully printed the contents of each file to the console.
-Ran getFileName from a designated list of files and all returned the correct file name.
-Ran fCreateFile and was able create the file with the correct content in a designated location and returned error if wrong.
Integration test ran within the chat class
-Successfully read in a file and returned its name. Next successfully copying those contents to a specific designated path.

**Comment by dawsonjones2020** [comment]
-Tested the three custom message-type widgets to make sure they stayed formatted in different-sized windows and messages
-Tested the main screen frames on different sizes and settings to make sure they rendered properly
-Tested the message box frame to make sure overloading the text box wouldn't result in an error

**Comment by piangno** [comment]
-Test 1: connect() method on the App class. It should prompt a message box to decide for client and server. Everything work as expected, there are more implementations needed in the method which should be done in the future sprint.
-Test 2: connect() method from the client side. The client attempts to connect with the server 5 times. Tested with correct and incorrect inputs(ip and port). It work as expected so far.
-Test 3: on_closing() method on the App class. The program should with all the connections. It closed as expected.

**Comment by mypleasure370** [comment]
- Test 1: messages are encrypted correctly 
- Test 2: messages are decrypted correctly
- Test 3: padding is removed from messages correctly

Specifics will be in documentation shortly :)
